#!/usr/bin/bash
~/.config/sway/inhibitors/pulse.sh || exit 1

swaylock --screenshots --clock --indicator --indicator-radius 100 --effect-blur 7x5 --ring-color 55cdfc --key-hl-color f7a8d8 --line-color 00000000 --inside-color 00000088 --separator-color 00000000 --grace 2 --fade-in 0.2
